### ISSUE TITLE
mancano i tag twittercard

### ISSUE THREAD

**Issue by mguidotto** [fevrcoding/fevrcoding.github.io#3]
alcuni articoli come reference

http://danyalzia.com/2015/06/30/adding-twitter-cards-to-jekyll/
http://aramzs.github.io/jekyll/social-media/2015/11/11/be-social-with-jekyll.html

**Comment by kino90** [comment]
Dovrebbe gia' farlo [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) .. Controllo appena ho un attimo
